management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/authdb
    password: 123456789
  application:
    name: JwtAuth-service
  jpa:
    hibernate:
      ddl-auto: update
application:
  security:
    jwt:
      expiration: 86400000
      key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
server:
  port: 8084