server:
  port: 8083
spring:
  application:
    name: theatre-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/theatredb
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver





